import type { Metadata } from 'next'
import { Html } from "next/document"
import Link from 'next/link';

import './globals.css'
import BlobTank from './components/BlobTank';
import Navbar from "./components/Navbar"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">      
      <body>
      <Navbar />
      {children}
      </body>
    </html>
  )
}