// This is the not-found.tsx file in the app directory
// This file is used to handle 404 errors in a Next.js application. It will be displayed when a user tries to access a page that does not exist. You can customize the content of this file to provide a better user experience, such as adding links to other pages or a search bar.
// This file is automatically generated by Next.js and should not be modified directly. Instead, you can create a custom 404 page by creating a new file in the app directory with the name not-found.tsx. This will override the default 404 page and allow you to customize the content and layout of the page.
// You can also use this file to handle other types of errors, such as 500 errors or 403 errors. To do this, you can create additional files in the app directory with the names 500.tsx and 403.tsx. These files will be used to handle the corresponding error codes and will override the default error pages provided by Next.js.

export default function NotFound() {
    return <h1>404 - Page Not Found</h1>;
}  