import type { Metadata } from 'next'
import { Html } from "next/document"
import Link from 'next/link';

import '../globals.css'
import Navbar from "../components/Navbar"
import BlobTankNetwork from '../components/BlobTankNetwork';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <BlobTankNetwork />
        {children}

      </body>
    </html>
  )
}